import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import './globals.css'
import { cookies } from 'next/headers'
import { UserSetter } from './_components/UserSetter'
import { ThemeChangeButton } from './_components/ThemeChangeButton(out)'
import { Logo } from './_components/Logo'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  const supabase = createServerComponentClient({ cookies })

  const { data: { user } } = await supabase.auth.getUser()

  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          <Logo />
          <UserSetter user={user} />
          <div className='z-10'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
