import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import './globals.css'
import { cookies } from 'next/headers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  const supabase = createServerComponentClient({ cookies })

  const user = await supabase.auth.getUser()

  console.log(user);

  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
